# Generated by Django 5.2.11 on 2026-02-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
